version: "3"
services:
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.5-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK=000
      - WEBUI_PORT=58080 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ./qb_config:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      - 58080:58080 # GUI
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 56881:56881
      - 56881:56881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
    restart: unless-stopped
