services:
  emby:
    image: emby/embyserver_arm64v8
    container_name: embyserver
    # runtime: nvidia # Expose NVIDIA GPUs
    # network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
      - TZ=Asia/Shanghai # 你的时区
    volumes:
      - ./data:/config # Configuration directory
      - /mnt:/mnt # Media directory
    ports:
      - 8096:8096 # HTTP port
    restart: unless-stopped
