version: "3"
services:
  moviePilot:
    image: jxxghp/moviepilot:latest
    ports:
      - 3000:3000 # 默认的webui控制端口
    volumes:
      - ./config:/config # 冒号左边请修改为你想保存配置的路径
      - /downloads:/downloads #设置下载路径
      - /root/.config/rclone:/moviepilot/.config/rclone #rclone配置文件映射
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker.sock映射 - 支持应用内重启
    environment:
      - TZ=Asia/Shanghai # 你的时区
      - AUTH_SITE=icc2022 # 认证站点冰激凌
      - ICC2022_UID=18128
      - ICC2022_PASSKEY=8b1c8dc008e6bbd455e9c53e3e2ff668
      - RCLONE_TRANSFERS=10 # rclone传输线程数
      - MOVIEPILOT_AUTO_UPDATE=release #重启时自动更新
      - MOVIE_RENAME_FORMAT={{title}} ({{year}}) [tmdbid={{tmdbid}}]/{{title}} ({{year}}){% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{% if releaseGroup %} - {{releaseGroup}}{% endif %}{{fileExt}}
      - TV_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %} [tmdbid={{tmdbid}}]/Season {{season}}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if episode %} - 第 {{episode}} 集{% endif %}{% if releaseGroup %} - {{releaseGroup}}{% endif %}{{fileExt}}
      # 下载设置
      - DOWNLOAD_PATH=/downloads #下载保存目录，注意：需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移 - 仅供参考
      - DOWNLOAD_MOVIE_PATH=/downloads #电影下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_TV_PATH=/downloads #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_ANIME_PATH=/downloads #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_CATEGORY=false #下载二级分类开关
      - TORRENT_TAG=MOVIEPILOT #种子标签
      # 媒体库
      - LIBRARY_PATH=/ #媒体库目录，多个目录使用,分隔
      - LIBRARY_MOVIE_NAME=/ #电影媒体库目录名，默认电影
      - LIBRARY_TV_NAME=/ #电视剧媒体库目录名，默认电视剧
      - LIBRARY_ANIME_NAME=/ #动漫媒体库目录名，默认电视剧/动漫
      - LIBRARY_CATEGORY=false # 媒体库二级分类开关
      - TRANSFER_TYPE=rclone_copy #整理转移方式，支持link/copy/move/softlink/rclone_copy/rclone_move
      # 插件库
      - PLUGIN_MARKET=https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/thsrite/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/honue/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/dandkong/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/Aqr-K/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/AnjoyLi/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/WithdewHua/MoviePilot-Plugins/main/,https://raw.githubusercontent.com/HankunYu/MoviePilot-Plugins/main/,https://github.com/almus2zhang/MoviePilot-Plugins,https://github.com/baozaodetudou/MoviePilot-Plugins,https://github.com/HankunYu/MoviePilot-Plugins/,https://github.com/InfinityPacer/MoviePilot-Plugins/,https://github.com/lingjiameng/MoviePilot-Plugins/
    restart: unless-stopped
    hostname: moviePilot
    container_name: moviePilot
     