version: "3"
services:
  moviePilot:
    image: jxxghp/moviepilot:latest
    ports:
      - 3000:3000 # 默认的webui控制端口
    volumes:
      - ./config:/config # 冒号左边请修改为你想保存配置的路径
      - ./downloads:/downloads #设置下载路径
      - /root/.config/rclone:/moviepilot/.config/rclone #rclone配置文件映射
      - /var/run/docker.sock:/var/run/docker.sock:ro # docker.sock映射 - 支持应用内重启
    environment:
      - TZ=Asia/Shanghai # 你的时区
      - AUTH_SITE=icc2022 # 认证站点冰激凌
      - ICC2022_UID=18128
      - ICC2022_PASSKEY=8b1c8dc008e6bbd455e9c53e3e2ff668
      - RCLONE_TRANSFERS=10 # rclone传输线程数
      - MOVIEPILOT_AUTO_UPDATE=release #重启时自动更新
      - MOVIE_RENAME_FORMAT={{title}} ({{year}}) [tmdbid={{tmdbid}}]/{{title}} ({{year}}){% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{% if releaseGroup %}-{{releaseGroup}}{% endif %}{{fileExt}}
      # 下载设置
      - DOWNLOAD_PATH=/downloads #下载保存目录，注意：需要将moviepilot及下载器的映射路径保持一致，否则会导致下载文件无法转移 - 仅供参考
      - DOWNLOAD_MOVIE_PATH=/downloads/Movies #电影下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_TV_PATH=/downloads/TV #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_ANIME_PATH=/downloads/Anime #电视剧下载保存目录，必须是DOWNLOAD_PATH的下级路径，不设置则下载到 DOWNLOAD_PATH
      - DOWNLOAD_CATEGORY=false #下载二级分类开关
      - TORRENT_TAG=MOVIEPILOT #种子标签
  # 媒体库
      - LIBRARY_PATH=/ #媒体库目录，多个目录使用,分隔
      - LIBRARY_MOVIE_NAME=电影 #电影媒体库目录名，默认电影
      - LIBRARY_TV_NAME=电视剧 #电视剧媒体库目录名，默认电视剧
      - LIBRARY_ANIME_NAME=动漫 #动漫媒体库目录名，默认电视剧/动漫
      - LIBRARY_CATEGORY=false # 媒体库二级分类开关
      - TRANSFER_TYPE=rclone_copy #整理转移方式，支持link/copy/move/softlink/rclone_copy/rclone_move
    restart: unless-stopped
    hostname: moviePilot
    container_name: moviePilot
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.5-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK=000
      - WEBUI_PORT=58080 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ./qb_config:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      - 58080:58080 # GUI
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 56881:56881
      - 56881:56881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
    restart: unless-stopped
     