version: "3"
services:
  moviePilot:
    image: jxxghp/moviepilot:latest
    ports:
      - 3000:3000 # 默认的webui控制端口
    volumes:
      - ./config:/config # 冒号左边请修改为你想保存配置的路径
      - ./downloads:/downloads #设置下载路径
      - /root/.config/rclone:/moviepilot/.config/rclone \ #rclone配置文件映射
      - /mnt:/mnt #rclone挂载路径
    environment:
      - TZ=Asia/Shanghai # 你的时区
      - AUTH_SITE=icc2022 # 认证站点冰激凌
      - ICC2022_UID=18128
      - ICC2022_PASSKEY=8b1c8dc008e6bbd455e9c53e3e2ff668
    restart: unless-stopped
    hostname: moviePilot
    container_name: moviePilot
  qbittorrent:
    image: linuxserver/qbittorrent:4.4.5-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK=000
      - WEBUI_PORT=58080 # 将此处修改成你欲使用的 WEB 管理平台端口 
    volumes:
      - ./qb_config:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      - 58080:58080 # GUI
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 56881:56881
      - 56881:56881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
    restart: unless-stopped
    