version: '3'
services:
  auto_symlink:
    image: shenxianmq/auto_symlink:latest
    container_name: auto_symlink
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8095:8095
    volumes:
      - ./config:/app/config
      - ./mnt/cd2:/volume1/CloudNAS:rslave
    restart: unless-stopped
